name: "Setup Android Environment"
description: "Setup the Android environment for CI/CD pipeline."
inputs:
  use_shorebird:
    description: "Whether to setup Shorebird."
    required: false
    default: "true"
  service_account_json:
    description: "Service Account"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Environment: SSH Key"
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ env.ssh_key }}
    - name: "Environment: Fastlane"
      run: |
        gem install fastlane
        echo ${{ inputs.service_account_json }} | base64 --decode > "fastlane/service_key.json"
        echo "json_key_file(\"fastlane/service_key.json\")" >> fastlane/Appfile
      shell: bash
      working-directory: android
